import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Whatsapp from "@/components/global/whatsapp/Whatsapp";
import SocialWidget from "@/components/global/socialmedia/SocialWidget";
import Script from "next/script";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});
export const metadata = {
  metadataBase: new URL('https://www.prakria.com'),
  alternates: {
    canonical: './'
  },
  title: {
    default: "PRAKRIA : Best Creative Marketing Agency in India",
    template: "%s - PRAKRIA",
  },
  description: "Generated by create next app",
  keywords: [
    "Best 360 marketing agency in Delhi",
    "360 marketing agency in India",
    "Best creative agency in Delhi India",
    "Creative marketing agency in Delhi India",
    "Best marketing agency in Delhi India",
    "Digital marketing agency in Delhi India",
    "Digital marketing services in Delhi India",
    "Performance marketing agency in Delhi India",
    "Social media marketing agency in Delhi India",
    "Best SEO agency in Delhi",
    "Best PPC marketing agency in Delhi",
    "Content marketing agency in Delhi India",
    "Influencer marketing agency in Delhi India",
    "Best branding agency in Delhi",
    "Brand strategy agency in Delhi India",
    "Packaging design company in Delhi India",
    "Best packaging design agency in Delhi",
    "Luxury packaging design agency in Delhi India",
    "Print media advertising agency in Delhi India",
    "3D animation studio in Delhi India",
    "Best VFX company in Delhi",
    "CGI studio in Delhi India",
    "AR VR development company in Delhi India",
    "Game development company in Delhi India",
    "Video production company in Delhi India",
    "Best film production company in Delhi",
    "Animation video production company in Delhi",
    "Website development company in Delhi India",
    "Best web development agency in Delhi",
    "best illustration agency in Delhi",
    "illustration agency in delhi",
    "Best illustration agency in Delhi NCR",
    "Illustration Companies in Delhi NCR",
    "3D & CGI agency in Delhi",
    "3D & CGI services in Delhi",
    "3D & CGI agency in Delhi NCR",
    "AR VR development agency",
    "creative advertising agency in Delhi"
  ],
  twitter: {
    card: "summary_large_image",
  },
  openGraph: {
    title: "PRAKRIA : Best Creative Marketing Agency in India",
    type: "website",
  },
};

import Providers from "@/components/Providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/favicon.ico" />
        {/* Google Tag Manager */}
        <Script id="gtm-script" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-KMGMRW7H');
          `}
        </Script>
        {/* End Google Tag Manager */}

      </head>
      <body
        className={`${playfairDisplay.className} ${playfairDisplay.variable} dark`}
      >

        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KMGMRW7H"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        {/* End Google Tag Manager (noscript) */}

        {/* Google tag (gtag.js) */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-TDS9XMGZG2"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-TDS9XMGZG2');
          `}
        </Script>

        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
