import {
  Inter,
  Hanken_Grotesk,
  Signika,
  Playfair_Display,
  Rubik,
} from "next/font/google";
import "./globals.css";
import Whatsapp from "@/components/global/whatsapp/Whatsapp";
import SocialWidget from "@/components/global/socialmedia/SocialWidget";

const inter = Rubik({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const signika = Playfair_Display({
  subsets: ["latin"],
});

const hankenGrotesk = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-hankenGrotesk",
  display: "swap",
});
export const metadata = {
  title: {
    default: "PRAKRIA : Best Creative Marketing Agency in India",
    template: "%s - PRAKRIA",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/favicon.ico"/>
      </head>
      <body
        className={`${signika.className} ${inter.variable} ${hankenGrotesk.variable} dark`}
      >
        <Whatsapp />
        <SocialWidget />
        {children}
      </body>
    </html>
  );
}
